import pygame

# Creating Window & Dots

SCREEN = WIDTH, HEIGHT = 300, 300
CELL_SIZE_BETWEEN_DOTS = 20
PADDING_BETWEEN_DOTS = 20 # SPACE BETWEEN DOTS
ROWS = COLUMNS = (WIDTH - 4*PADDING_BETWEEN_DOTS) // CELL_SIZE_BETWEEN_DOTS # ROWS & COLUMNS = (300(WIDTH) - 80 (PADDING * 4)) / 20 = (300 - 80) / 20 = 220 / 20 = 11 -> 11 ROWS & COLUMNS
print(ROWS, COLUMNS)